global:
  project: agylam
  ref: "dev"
  isTag: false
  registry: ""

backend:
  image: agylam/back
  replicas: 2
  ports:
    - 3000
    - 8080

frontend:
  image: agylam/front
  replicas: 2
  ports:
    - 80

ingress: {}

postgresql:
  enabled: true
  fullnameOverride: postgres
  image:
    tag: 15.5.0-debian-11-r22
  commonAnnotations:
    helm.sh/hook: pre-install,pre-upgrade
  auth:
    database: agylam
    username: changeme
    password: changeme

redis:
  enabled: true
  fullnameOverride: redis
  replica:
    replicaCount: 0
    persistence:
      enabled: false
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

ENV: { }

SECRETS: { }
