global:
  tier: "dev"

ENV:
  BURL: http://backend:81
  FRONTEND_PORT: 80
  PGPORT: "5432"
  PGDATABASE: agylam
  PGHOST: postgres
  BACKEND_PORT: "81"
  SESSION_TIME: 1d
  JWT_EXPIRESIN: 1h

SECRETS:
  JWT_SECRET: "{{DEV_JWT_SECRET}}"
  PGUSER: "{{DEV_PGUSER}}"
  PGPASSWORD: "{{DEV_PGPASSWORD}}"