global:
  tier: "dev"

ENV:
  dev:
    BURL: http://backend:3000
    FRONTEND_PORT: 80
    PGPORT: "5432"
    PGDATABASE: agylam
    PGHOST: postgres
    BACKEND_PORT: 3000
    SESSION_TIME: 1d
    JWT_EXPIRESIN: 1h
    WS_SERVER_PORT: 8080

postgresql:
  enabled: true
  auth:
    postgresPassword: "{{ DEV_PGPASSWORD }}"
    username: "{{ DEV_PGUSER }}"
    password: "{{ DEV_PGPASSWORD }}"

SECRETS:
  dev:
    JWT_SECRET: "{{ DEV_JWT_SECRET }}"
    PGUSER: "{{ DEV_PGUSER }}"
    PGPASSWORD: "{{ DEV_PGPASSWORD }}"