global:
  tier: "prod"
  isTag: true

postgresql:
  enabled: false

SECRETS:
  JWT_SECRET: "${{ secrets.PROD_JWT_SECRET }}"
  PGUSER: "${{ secrets.PROD_PGUSER }}"
  PGPASSWORD: "${{ secrets.PROD_PGPASSWORD }}"