global:
  tier: "prod"
  ref: "tag"
  isTag: true

ENV:
  production:
    BURL: http://backend:81
    FRONTEND_PORT: 80
    PGPORT: "5432"
    PGDATABASE: agylam
    BACKEND_PORT: "81"
    SESSION_TIME: 1d
    JWT_EXPIRESIN: 1h
    WS_SERVER_PORT: 8080

postgresql:
  enabled: false

SECRETS:
  production:
    JWT_SECRET: "{{ PRODUCTION_JWT_SECRET }}"
    PGUSER: "{{ PRODUCTION_PGUSER }}"
    PGPASSWORD: "{{ PRODUCTION_PGPASSWORD }}"
    PGHOST: "{{ PRODUCTION_PGHOST }}"
