global:
  tier: "prod"
  isTag: true

ENV:
  BURL: http://backend:81
  FRONTEND_PORT: 80
  PGPORT: "5432"
  PGDATABASE: agylam
  PGHOST: postgres
  BACKEND_PORT: "81"
  SESSION_TIME: 1d
  JWT_EXPIRESIN: 1h

postgresql:
  enabled: false

SECRETS:
  JWT_SECRET: "${{ secrets.PROD_JWT_SECRET }}"
  PGUSER: "${{ secrets.PROD_PGUSER }}"
  PGPASSWORD: "${{ secrets.PROD_PGPASSWORD }}"
  PGHOST: "${{ secrets.PROD_PGHOST }}"
