global:
  tier: "prod"
  ref: "tag"
  isTag: true

ENV:
  production:
    BURL: http://backend:3000
    FRONTEND_PORT: 80
    PGPORT: "5432"
    PGDATABASE: agylam
    BACKEND_PORT: 3000
    SESSION_TIME: 1d
    JWT_EXPIRESIN: 1h
    WS_SERVER_PORT: 8080

ingress:
  baseDomain: ["agylam.online", "xn----8sbccs3afw.xn--p1ai"]
  toService: frontend

postgresql:
  enabled: false

SECRETS:
  production:
    JWT_SECRET: "{{ PRODUCTION_JWT_SECRET }}"
    PGUSER: "{{ PRODUCTION_PGUSER }}"
    PGPASSWORD: "{{ PRODUCTION_PGPASSWORD }}"
    PGHOST: "{{ PRODUCTION_PGHOST }}"
    CLOUD_VOICE_API_KEY: "{{ PRODUCTION_CLOUD_VOICE_API_KEY }}"
    S3_ENDPOINT: "{{ PRODUCTION_S3_ENDPOINT }}"
    S3_REGION: "{{ PRODUCTION_S3_REGION }}"
    S3_BUCKET: "{{ PRODUCTION_S3_BUCKET }}"
    S3_ACCESS_KEY_ID: "{{ PRODUCTION_S3_ACCESS_KEY_ID }}"
    S3_SECRET_ACCESS_KEY: "{{ PRODUCTION_S3_SECRET_ACCESS_KEY }}"
    REDIS_URL: redis-master:6379
