global:
  tier: "stage"
  ref: "stage"

ENV:
  stage:
    BURL: http://backend:3000
    FRONTEND_PORT: 80
    PGPORT: "5432"
    PGDATABASE: agylam
    PGHOST: postgres
    BACKEND_PORT: 3000
    SESSION_TIME: 1d
    JWT_EXPIRESIN: 1h
    WS_SERVER_PORT: 8080

postgresql:
  enabled: true
  auth:
    postgresPassword: "{{ STAGE_PGPASSWORD }}"
    username: "{{ STAGE_PGUSER }}"
    password: "{{ STAGE_PGPASSWORD }}"

SECRETS:
  stage:
    JWT_SECRET: "{{ STAGE_JWT_SECRET }}"
    PGUSER: "{{ STAGE_PGUSER }}"
    PGPASSWORD: "{{ STAGE_PGPASSWORD }}"