global:
  tier: "stage"
  ref: "stage"

ENV:
  BURL: http://backend:81
  FRONTEND_PORT: 80
  PGPORT: "5432"
  PGDATABASE: agylam
  PGHOST: postgres
  BACKEND_PORT: "81"
  SESSION_TIME: 1d
  JWT_EXPIRESIN: 1h

postgresql:
  enabled: true
  auth:
    postgresPassword: "${{ secrets.STAGE_PGPASSWORD }}"
    username: "${{ secrets.STAGE_PGUSER }}"
    password: "${{ secrets.STAGE_PGPASSWORD }}"

SECRETS:
  JWT_SECRET: "${{ secrets.STAGE_JWT_SECRET }}"
  PGUSER: "${{ secrets.STAGE_PGUSER }}"
  PGPASSWORD: "${{ secrets.STAGE_PGPASSWORD }}"