global:
  tier: "stage"
  ref: "stage"

ENV:
  stage:
    BURL: http://backend:3000
    FRONTEND_PORT: 80
    PGPORT: "5432"
    PGDATABASE: agylam
    PGHOST: postgres
    BACKEND_PORT: 3000
    SESSION_TIME: 1d
    JWT_EXPIRESIN: 1h
    WS_SERVER_PORT: 8080

postgresql:
  enabled: true
  auth:
    postgresPassword: "{{ STAGE_PGPASSWORD }}"
    username: "{{ STAGE_PGUSER }}"
    password: "{{ STAGE_PGPASSWORD }}"

SECRETS:
  stage:
    CLOUD_VOICE_API_KEY: "{{ STAGE_CLOUD_VOICE_API_KEY }}"
    S3_ENDPOINT: "{{ STAGE_S3_ENDPOINT }}"
    S3_REGION: "{{ STAGE_S3_REGION }}"
    S3_BUCKET: "{{ STAGE_S3_BUCKET }}"
    S3_ACCESS_KEY_ID: "{{ STAGE_S3_ACCESS_KEY_ID }}"
    S3_SECRET_ACCESS_KEY: "{{ STAGE_S3_SECRET_ACCESS_KEY }}"
