{{- define "secret_app" -}}
{{- $ := index . 0 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.global.project }}-secret
data:
  {{- range $k, $v := (index $.Values.SECRETS $.Values.werf.env) }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end -}}
{{- end -}}

{{- include "secret_app" (list $) -}}