{{ define "service_app" }}
{{- $ := index . 0 -}}
{{- $container := index . 1 -}}
{{- $containerSpec := get $.Values $container -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $container }}
spec:
  ports:
  {{- range $p := $containerSpec.ports }}
  - name: http-{{ $p }}
    port: {{ $p }}
    protocol: TCP
    targetPort: {{ $p }}
  {{- end }}
  selector:
    app: {{ $.Values.global.project }}-{{ $container }}
  type: ClusterIP
{{ end }}

{{ include "service_app" (list $ "backend") }}
---
{{ include "service_app" (list $ "frontend") }}