name: Build & Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        modules: [front, back]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DK_USERNAME }}
          password: ${{ secrets.DK_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.modules }}/docker/Dockerfile
          context: ${{ matrix.modules }}
          push: true
          build-args: |
            ARG_BUILD_VERSION=${{ github.ref_name }}
          tags: agylam/${{ matrix.modules }}:${{ github.ref_name }}


  deploy:
    runs-on: self-hosted
    environment: production
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - run: helm dependency update .helm/agylam

      - name: Helm Deploy
        uses: vimeda/helm@v1.7.0
        with:
          release: 'agylam-prod'
          namespace: 'agylam-prod'
          chart: '.helm/agylam'
          token: '${{ github.token }}'
          atomic: true
          secrets: ${{ toJSON(secrets) }}
          values: |
            global:
              ref: "${{ github.ref_name }}"
          value-files: >-
            [
              ".helm/agylam/common-values.yaml", 
              ".helm/agylam/prod-values.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'