name: Build & Push

on:
  push:
    branches:
      - "noner"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DK_USERNAME }}
          password: ${{ secrets.DK_TOKEN }}

      - name: BackEnd Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./back
          file: ./back/docker/Dockerfile
          push: true
          tags: agylam/back:${{ github.ref_name }}

      - name: FrontEnd Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./front
          file: ./front/docker/Dockerfile
          push: true
          tags: agylam/front:${{ github.ref_name }}

      - name: Docker Pull & Up
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEYPASS }}
          script: |
            cd stand && docker-compose pull && docker-compose up -d
