name: Build & Deploy

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    strategy:
      matrix:
        modules: [front, back]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DK_USERNAME }}
          password: ${{ secrets.DK_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.modules }}/docker/Dockerfile
          context: ${{ matrix.modules }}
          push: true
          build-args: |
            ARG_BUILD_VERSION=${{ github.ref_name }}
          tags: agylam/${{ matrix.modules }}:${{ github.ref_name }}


  deploy:
    runs-on: self-hosted
    environment: dev
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      # - name: set up ssh tunel
      #   run: |
      #     mkdir ~/.ssh
      #     ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      #     eval `ssh-agent -s`
      #     ssh-add - <<< "${{ secrets.SSH_KEY }}"
      #     ssh -fN -v -L 8443:192.168.49.2:8443 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - run: helm dependency update .helm/agylam

      - name: Helm Deploy
        uses: vimeda/helm@v1.7.0
        with:
          release: 'agylam-dev'
          namespace: 'agylam-dev'
          chart: '.helm/agylam'
          token: '${{ github.token }}'
          atomic: true
          secrets: ${{ toJSON(secrets) }}
          value-files: >-
            [
              ".helm/agylam/common-values.yaml", 
              ".helm/agylam/dev-values.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'
