name: Converge PROD

on:
  push:
    tags:
      - '*'

jobs:
  converge:
    name: converge
    runs-on: self-hosted
    environment: production
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Inject secrets to yaml files
          uses: none0nfg/yaml-secrets-injector@v0.0.1
          with:
            inject_files: |-
              .helm/agylam/prod-values.yaml
            secrets: ${{ toJSON(secrets) }}

        - name: Install werf
          uses: werf/actions/install@v1.2

        - name: Run script
          run: |
            . $(werf ci-env github --as-file)
            docker login -u agylam -p ${{ secrets.DK_TOKEN }}
            werf helm dependency build .helm/agylam
            werf converge --debug --env=production --atomic --values .helm/agylam/common-values.yaml --values .helm/agylam/prod-values.yaml --repo agylam/web --repo-docker-hub-token='${{ secrets.DK_TOKEN }}' --repo-docker-hub-username=agylam
          env:
            WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_64 }}
