name: Build & Deploy

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    strategy:
      matrix:
        modules: [front, back]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DK_USERNAME }}
          password: ${{ secrets.DK_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.modules }}/docker/Dockerfile
          context: ${{ matrix.modules }}
          push: true
          build-args: |
            ARG_BUILD_VERSION=${{ github.ref_name }}
          tags: agylam/${{ matrix.modules }}:${{ github.ref_name }}


  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - name: set up kube_config
        run: |
          mkdir ~/.kube
          echo -n ${{ secrets.CICD_B64CONFIG }} | base64 -d > ~/.kube/config

      - name: set up ssh tunel
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          ssh -fN -v -L 8443:192.168.49.2:8443 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - uses: none0nfg/install-helm-action@v0.0.1
        with:
            helm_version: v3.12.0
            kubectl_version: v1.27.3

      - name: Deploy dev
        run: |
          helm upgrade agylam-dev .helm/agylam/ --install --timeout 60s --atomic --wait --cleanup-on-fail -f .helm/agylam/common-values.yaml -f .helm/agylam/dev-values.yaml --set global.ref=${{ github.ref_name }}